# Generated by Django 2.2.4 on 2019-09-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endgam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Latest_news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(auto_now=True)),
                ('news_title', models.CharField(max_length=100)),
                ('news_desc', models.TextField()),
                ('news_img', models.ImageField(upload_to='newsimg')),
            ],
        ),
    ]
